### ISSUE TITLE
Example Projects RollingClock short day names overlap long day names

### ISSUE THREAD

**Issue by smcferrin** [witnessmenow/ESP32-Cheap-Yellow-Display#101]
When RollingClock goes from "Saturday" to "Sunday" the displayed day is "SSundayy".
Need to clear the day before drawing over older days. 

![IMG_7874](https://github.com/witnessmenow/ESP32-Cheap-Yellow-Display/assets/78212/80b8d150-771f-4435-b6ab-00e5e48e9cf1)

Thanks for sharing your work!

**Comment by witnessmenow** [comment]
Should be fixed in both versiond now
