### ISSUE TITLE
Analog Video Signal (NTSC) with CYD

### ISSUE THREAD

**Issue by ArifShariar** [witnessmenow/ESP32-Cheap-Yellow-Display#106]
So, I was planning on using an FPV camera, which outputs video signals as NTSC to make a DIY camera project. I want to use the screen as a preview/gallery viewer. I have not worked with NTSC with ESP-32 before. Any help will be appreciated. The image of the camera is given below.
![54c82784-0309-4edf-8330-5f44e139f2fc](https://github.com/witnessmenow/ESP32-Cheap-Yellow-Display/assets/43639863/d5a39913-2f33-4fc6-9cf6-e5cfe7fdcbd3)

**Comment by witnessmenow** [comment]
I think this question is beyond the scope of the repo. It's more of a general esp32 question
