### ISSUE TITLE
Is this something we should know about?

### ISSUE THREAD

**Issue by Grey-Lancaster** [witnessmenow/ESP32-Cheap-Yellow-Display#116]
Or do you already know?

https://registry.platformio.org/libraries/rzeldent/esp32_smartdisplay

Grey

**Comment by olivluca** [comment]
I actually used it to write my first (and only) CYD project.
I think it should be mentioned somewhere in this repository.

**Comment by olivluca** [comment]
This is a duplicate of issue #34
