### ISSUE TITLE
Everything needs to be updated

### ISSUE THREAD

**Issue by Grey-Lancaster** [witnessmenow/ESP32-Cheap-Yellow-Display#130]
This may have been great once upon a time, but examples no longer compile in Arduino or Paltfromio.

Problem with Platformio is spiffs is no longer supported.

Can anyone show me how to do the [slideshow example](https://github.com/witnessmenow/ESP32-Cheap-Yellow-Display/tree/main/Examples/Showcases/1-Slideshow) for example with current library's?

Thanks,
Grey

**Comment by Grey-Lancaster** [comment]
for example the [LVGL demo](https://github.com/witnessmenow/ESP32-Cheap-Yellow-Display/tree/main/Examples/LVGL) does not work with the latest and greatest LVGL library v(.0 it has to be v8.3.9

**Comment by Grey-Lancaster** [comment]
I cannot seem to find what you must be talking about.  I just looked and apparently the was or is a standalone Platformio IDE.  But whenever I click on download IDE it goes to Platformio for VS code which is  what I have and SPIFFS is no longer supported.

https://community.platformio.org/t/problem-with-spiffs/36837

![image](https://github.com/witnessmenow/ESP32-Cheap-Yellow-Display/assets/20055899/b8c73f0a-f976-4c7f-a3d2-ed96c1aedb14)

**Comment by witnessmenow** [comment]
> I cannot seem to find what you must be talking about. I just looked and apparently the was or is a standalone Platformio IDE. But whenever I click on download IDE it goes to Platformio for VS code which is what I have and SPIFFS is no longer supported.
> 
> https://community.platformio.org/t/problem-with-spiffs/36837
> 
> ![image](https://private-user-images.githubusercontent.com/20055899/300467717-b8c73f0a-f976-4c7f-a3d2-ed96c1aedb14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1NDMzNjgsIm5iZiI6MTcwNjU0MzA2OCwicGF0aCI6Ii8yMDA1NTg5OS8zMDA0Njc3MTctYjhjNzNmMGEtZjk3Ni00YzdmLWEzZDItZWQ5NmMxYWVkYjE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDE1NDQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwZjIzNGZmNzNhNDg0NmY2MWU1Y2M0NGQxOTljMGNkYTc5OTg2M2IzMTM0YjgzMzQyMjBiYWYwNGExMDJlMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W61vnFH4TJ7SfTEl8t7THlzlEOSoAI74UHQO9C1pYKU)

That looks to relate to esp8266 not esp32

**Comment by Grey-Lancaster** [comment]
That looks to relate to esp8266 not esp32
You might be right, but it still gives an error. Are you using VS Code with platformio ?
 In his examples he uses littlefs
https://registry.platformio.org/libraries/bodmer/TFT_eSPI/examples/PNG_Images

When I build it does not include spiffs

Found 34 compatible libraries
Scanning dependencies...
Dependency Graph
|-- TFT_eSPI @ 2.5.43
|-- JPEGDEC @ 1.4.0
|-- SdFat @ 2.2.2
|-- XPT2046_Bitbang_Slim @ 2.0.0
|-- SPI @ 2.0.0
|-- FS @ 2.0.0
|-- LittleFS @ 2.0.0
Building in release mode
Compiling .pio\build\cyd2usb\src\src\CYC_Slideshow.cpp.o

Successfully created esp32 image.
Compiling .pio\build\cyd2usb\lib4c1\FS\FS.cpp.o
Compiling .pio\build\cyd2usb\lib4c1\FS\vfs_api.cpp.o
In file included from .pio/libdeps/cyd2usb/TFT_eSPI/TFT_eSPI.h:101,
                 from src/CYC_Slideshow.cpp:14:
.pio/libdeps/cyd2usb/TFT_eSPI/Processors/TFT_eSPI_ESP32.h:139:12: fatal error: SPIFFS.h: No such file or directory

****************************************************************
* Looking for SPIFFS.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:SPIFFS.h"
* Web  > https://registry.platformio.org/search?q=header:SPIFFS.h
*
****************************************************************

**Comment by Grey-Lancaster** [comment]
1000 pardons
SumB*tch
https://github.com/witnessmenow/ESP32-Cheap-Yellow-Display/tree/main/Examples/Showcases/1-Slideshow
The Arduino code works GREAT if you follow directions
I installed XPT2046_Bitbang which did not work.
XPT2046_Bitbang_Slim (SLIM) works great. Touch moves to next picture or the delay does.
Love it !!
Platformio VS code still fails, but who cares if Arduino works,
