### ISSUE TITLE
Troubleshooting: Linux Mint users may not be able to flash

### ISSUE THREAD

**Issue by LyimeS** [witnessmenow/ESP32-Cheap-Yellow-Display#187]
I spent a few hours trying to upload the example code to the board I received today. The Arduino IDE detected a serial device, but every time I attempted to upload, it returned the error "Failed to connect." Later, I realized that the serial port detected by the IDE wasn't the ESP32 but rather another device on my laptop. 

After hours of research, I found [this issue](https://github.com/arduino/arduino-ide/issues/1788) mentioning that a pre-installed software, brltty, was silently blocking the CH340 USB driver. The workaround (for now) is to uninstall brltty: `sudo apt-get remove brltty`

**Comment by TheNitek** [comment]
Part of the troubleshooting guide by now: https://github.com/witnessmenow/ESP32-Cheap-Yellow-Display/blob/main/TROUBLESHOOTING.md#cannot-upload
