### ISSUE TITLE
Examples should be auto compiled to verify they at least compile

### ISSUE THREAD

**Issue by witnessmenow** [witnessmenow/ESP32-Cheap-Yellow-Display#23]
https://github.com/witnessmenow/F1-Arduino-Notifications/blob/main/.github/workflows/test-build.yml

**Comment by TheNitek** [comment]
Implemented by https://github.com/witnessmenow/ESP32-Cheap-Yellow-Display/pull/69

**Comment by clach04** [comment]
Can this be closed now?

**Comment by witnessmenow** [comment]
I think to finish this out we need to exclude files that don't make sense to be webflashed like hello radio
