### ISSUE TITLE
Config User_Setup.h is too compilcated

### ISSUE THREAD

**Issue by yooo1999** [witnessmenow/ESP32-Cheap-Yellow-Display#231]
I need to config [User_Setup.h](https://github.com/TheNitek/ESP32-Cheap-Yellow-Display/blob/main/DisplayConfig/User_Setup.h) for my esp32-2432s028 (2 usb ports),but it's too compilated .
Maybe you can set another easier way to config that ? maybe set some User_Setup.h for each model?

**Comment by amirzohaib** [comment]
There is a User_Setup.h provided by RandomNerdTutorials, it is for 1 usb but works on my 2 usb as well

**Comment by TheNitek** [comment]
Configs for both variantes are available here in the repo https://github.com/witnessmenow/ESP32-Cheap-Yellow-Display/tree/main/DisplayConfig and proofen to work with the examples.
