### ISSUE TITLE
colors.

### ISSUE THREAD

**Issue by rocco99** [witnessmenow/ESP32-Cheap-Yellow-Display#271]
TFT_BLACK displays white, also cannot find a way to rotate text to be viewed in landscape orientation. Other colors also not correct.

**Comment by rocco99** [comment]
I meant tft.fillScreen(TFT_BLACK) shows a white screen.

**Comment by dave0003** [comment]
I'd recommend checking to make sure you're using the right User_Setup.h.  If your CYD version has 2 usb ports, you'll want to use the CYD2USB version.  I noticed something similar when I was using the wrong version.

https://github.com/witnessmenow/ESP32-Cheap-Yellow-Display/tree/main/DisplayConfig

**Comment by rocco99** [comment]
Thanks. I'll try that out and let you know if it works

**Comment by rocco99** [comment]
That did the trick. Thanks again.

**Comment by rocco99** [comment]
It worked out well. Thank you. I made a simple calculator that I would like to share as a basic example. But I have never posted anything on github . How do I post my code so that others can benefit from it?
