### ISSUE TITLE
Please add a copy of manufacturer archive

### ISSUE THREAD

**Issue by ellensp** [witnessmenow/ESP32-Cheap-Yellow-Display#28]
You guy's might want to add a full copy of the manufacturers archive for this display to this repo before it vanishes 

http://pan.jczn1688.com/directlink/1/ESP32%20module/2.8inch_ESP32-2432S028R.rar

Includes, among other things LVGL demo, which is why I went looking for it.

I see your comment that you sourced some data from this file, but discarded the rest, this seems wrong to disregard aditional information and examples provided.

**Comment by witnessmenow** [comment]
I added my reasons for what I discarded in this readme:

https://github.com/witnessmenow/ESP32-Cheap-Yellow-Display/blob/main/OriginalDocumentation/Readme.md

The examples are probably ok to add, but adding 900mb (!?) of code to this repo doesn't seem like a very good idea to me!

**Comment by ellensp** [comment]
well please consider adding in the LVGL examples, its one of the selling points of the display

**Comment by omnisy** [comment]
If adding putting the file in the repo is not an option then the repo owner could create an Internet Archive account and put the file there.
https://help.archive.org/help/uploading-a-basic-guide/

Here are file hashes for `2.8inch_ESP32-2432S028R.rar`
SHA1 `b164e7e8507ad50aa2bd4f3fd76d57b2a65f81b8`
SHA256 `21a1757aa3d1a836b0c41c7da653412b8a67928f5454ecc032c579876f674c3e`
SHA512 `9275ab578e7d962617ed7f1fc8928a95f92bbb56e126bfe961c153e050e2d0caa7c81ab2ad3c0e8c64d6339e8e7d6cb5a481c7bd54faa0dbb8ab47ac20a6b292`

The file was downloaded from http://pan.jczn1688.com/directlink/1/ESP32%20module/2.8inch_ESP32-2432S028R.rar a few minutes ago
