### ISSUE TITLE
Add info on a simple speaker solution

### ISSUE THREAD

**Issue by witnessmenow** [witnessmenow/ESP32-Cheap-Yellow-Display#3]
There is an amp and a connector for a simple speaker built into the CYD, so it would be great if simple solution to use it. Preferably that is ready to go out of the box.

The JST connector seems to be a 2 pin 1.25mm pitch connector.

This is a potential option: https://s.click.aliexpress.com/e/_mttu5ck

I will buy it and see does it work

**Comment by AllanOricil** [comment]
Did it work? @witnessmenow
