### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [witnessmenow/ESP32-Cheap-Yellow-Display#37]
Hello!

I found your project from https://hackaday.com/2023/10/28/cheap-yellow-display-builds-community-through-hardware/

Could you please add information about the license of this repository — is it allowed to copy, change and use the code in any purpose?
It would be great to see any popular open source license.

**Comment by witnessmenow** [comment]
Thanks for the reminder, will add it today.

Will be MIT

Only exception is the "original documentation" folder, I don't have any right to license that

**Comment by witnessmenow** [comment]
Added in 8dec5274682149556660df7ccffd629c0dec6dce

Thanks!

**Comment by vazhnov** [comment]
MIT — amazing! Thank you!
