### ISSUE TITLE
Add List of GPIO pins to Readme

### ISSUE THREAD

**Issue by daxliniere** [witnessmenow/ESP32-Cheap-Yellow-Display#38]
Hey there, I discovered this great project via Hackaday. I was curious which GPIO pins were available, but couldn't find that list anywhere on this repo. Could you add it to the documentation, please?
Cheers!
Dax

**Comment by witnessmenow** [comment]
Hi Dax

This is one where I've actually done the work already but I just haven't actually linked it I think!

https://github.com/witnessmenow/ESP32-Cheap-Yellow-Display/blob/main/PINS.md

**Comment by daxliniere** [comment]
Thanks Brian! That's perfect. Maybe a link to that doc could go on the main page?

**Comment by witnessmenow** [comment]
Added to the readme in 8dec5274682149556660df7ccffd629c0dec6dce

Thanks!
