### ISSUE TITLE
Use as KlipperScreen

### ISSUE THREAD

**Issue by Mordevolt** [witnessmenow/ESP32-Cheap-Yellow-Display#39]
Found this example of using similar display as 3d printer Klipper Screen addon.
Would be perfect if somebody could write detailed instructions for everyone, just like in other 3d print related project: 
https://github.com/xperiments-in/xtouch
https://www.reddit.com/r/klippers/comments/12fy4qb/18_klipperscreen_on_esp32_and_35_display/

**Comment by witnessmenow** [comment]
Looks like a cool project. Not something I'll be able to contribute to though as I don't have klipper
