### ISSUE TITLE
Add an example for speaker support

### ISSUE THREAD

**Issue by witnessmenow** [witnessmenow/ESP32-Cheap-Yellow-Display#4]
Different from #3 , this is the code for getting the speaker working

**Comment by witnessmenow** [comment]
@jonnybergdahl added this

https://github.com/witnessmenow/ESP32-Cheap-Yellow-Display/tree/main/Examples/Basics/7-HelloRadio

**Comment by tjamesw123** [comment]
Just wanted to leave a note that this example may need to be updated to account for the rewrite of the i2s lib for ESP32 if you want to keep it up to date. You probably already know this as the example has a compatible label on it but I thought I would say it anyway
