### ISSUE TITLE
Add physical dimensions to the README

### ISSUE THREAD

**Issue by scottchiefbaker** [witnessmenow/ESP32-Cheap-Yellow-Display#50]
Can you please add the physical dimensions of the LCD display, and possibly the external dimensions of the PCB to the README. It's hard to gauge it's size based on the pictures I've seen online.

I **love** the idea of this project. I ordered a CYB to play around with based entirely off of your YouTube video and the existence of this GitHub. Keep up the good work.

**Comment by kf106** [comment]
Screen is about 6.5cm by 4.5cm
Board is about 8.5cm by 5cm

**Comment by TheNitek** [comment]
You can find them dimensions here: https://github.com/witnessmenow/ESP32-Cheap-Yellow-Display/blob/main/OriginalDocumentation/3-Structure_Diagram/Dimensions.png
