### ISSUE TITLE
Wrong colors

### ISSUE THREAD

**Issue by hello-world-dot-c** [witnessmenow/ESP32-Cheap-Yellow-Display#76]
I've just got myself one CYD and getting started. I went through the set up for lcgl (lv_conf.h) and TFT_eSPI (User_Setup.h). I can build the LVGL example and in principle, everything works but the colors are all "negative", looking like this:

![image](https://github.com/witnessmenow/ESP32-Cheap-Yellow-Display/assets/57991555/66889ce7-2b5b-4317-9d9b-854045e0501d)

When I use tft.invertDisplay() it looks better but the colors are "washed out" , the red here is very pale and the green looks like a grey:

![image](https://github.com/witnessmenow/ESP32-Cheap-Yellow-Display/assets/57991555/8743265d-8c8e-4de5-abc8-4b35e1a9751d)

This is how the demo looked when I received the display:

![image](https://github.com/witnessmenow/ESP32-Cheap-Yellow-Display/assets/57991555/d2ff1d5d-842f-4b44-99d7-591dc82200c0)

Anybody knows how to fix this? LV_COLOR_16_SWAP 1 in lv_conf.h doesn't help and screws the colors up completely.

**Comment by witnessmenow** [comment]
This is a known issue with the version with two USB ports.

You've already sorted the first issue of the inverted colours, there is some discussion about fixing the colours here:

https://github.com/Bodmer/TFT_eSPI/issues/2985

**Comment by hello-world-dot-c** [comment]
Cool, that fixed it for me, thanks!
