### ISSUE TITLE
WiFi and TFT simultaneous

### ISSUE THREAD

**Issue by fritzbaratto** [witnessmenow/ESP32-Cheap-Yellow-Display#77]
Why doesn't work WiFi and TFT at the same time in my CYD?

**Comment by witnessmenow** [comment]
You'll have to give more info because it does for me

**Comment by fritzbaratto** [comment]
Hi Brian, IT WORKS,!
I had a wrong board selected in Arduino IDE...
sorry,
Fritz

**Comment by witnessmenow** [comment]
Great!
