### ISSUE TITLE
Unable to get the touchscreen to work

### ISSUE THREAD

**Issue by alanesq** [witnessmenow/ESP32-Cheap-Yellow-Display#92]
In case anyone else has this issue, I was unable to get any response from the touchscreen
I am using Arduino IDE v2.2.1 on Linux

In the end I found that if I replace the line:     SPIClass mySpi = SPIClass(VSPI);
                                                             with:   SPIClass mySpi = SPIClass(HSPI);

It resolved the issue :-)

**Comment by peteDDD** [comment]
Well isn't that interesting.   I found just the opposite as I was trying to get the lgvl examples and demos running...  The  [touch test](https://github.com/witnessmenow/ESP32-Cheap-Yellow-Display/tree/main/Examples/Basics/2-TouchTest)  uses SPIClass(VSPI).  But the  [lgvl examples](https://github.com/witnessmenow/ESP32-Cheap-Yellow-Display/tree/main/Examples/LVGL) use SPIClass(HSPI).  Until I changed that to SPIClass(VSPI), I got no touch response in the lgvl examples.
