### ISSUE TITLE
Getting touch working in LGVL examples

### ISSUE THREAD

**Issue by peteDDD** [witnessmenow/ESP32-Cheap-Yellow-Display#97]
The LGVL example uses the following 
`SPIClass mySpi = SPIClass(HSPI);`
which is different than the TouchTest which uses 
`SPIClass mySpi = SPIClass(VSPI);`

I found I could not get the touch working in the LGVL examples without changing this around line 30
```
//SPIClass mySpi = SPIClass(HSPI); // touch does not work with this setting
SPIClass mySpi = SPIClass(VSPI);  // critical to get touch working
```
The CYD board I am using is labeled ESP32-2432S028

**Comment by paelzer** [comment]
Hello, happy new year!!

The same goes for my display version which is also mentioning "ESP32-2432S028" but it's one of these which have two USB ports (micro-USB and USB-C).
Touch functionality is **only** working with:

**SPIClass mySpi = SPIClass(VSPI);**

This is my board:
![PXL_20240102_124326093](https://github.com/witnessmenow/ESP32-Cheap-Yellow-Display/assets/16374477/8d408611-cd07-4350-a393-b6211a023bd1)

**Comment by Grey-Lancaster** [comment]
@paelzer @peteDDD
Same baord tft espi example works
cannot get the LVGL example to compile
copied the 2 folders to src
I see the file is there?
Using LVGL V9.0  should I uise something older?

F:\Users\greyl\Documents\Arduino\libraries\lvgl\src\demos\benchmark\lv_demo_benchmark.c:25:10: fatal error: ../../src/display/lv_display_private.h: No such file or directory
 #include "../../src/display/lv_display_private.h"

**Comment by Grey-Lancaster** [comment]
/**
 * @file lv_conf.h
 * Configuration file for v8.3.9
 */

let me try that

**Comment by Grey-Lancaster** [comment]
IT WORKS !!!
yes have to change SPIClass mySpi = SPIClass(VSPI);  // critical to get touch working
Thanks for that

Is this how it is supposed to look?

![image](https://github.com/witnessmenow/ESP32-Cheap-Yellow-Display/assets/20055899/dec1216c-ba75-48c5-aee0-e2162fb2b76e)

**Comment by scudrunner** [comment]
This would be helpful as note somewhere in the README or in the example.  I had the same issues, and did not catch the difference in the examples between HSPI and VSPI

**Comment by anibarro** [comment]
I found the exact opposite, had to change from VSPI to HSPI to get it working...

**Comment by TheNitek** [comment]
LVGL examples are using VSPI now, so this is fixed

**Comment by Patsjemoe** [comment]
Hi, in which file is this ?

**Comment by dolfelt** [comment]
I am trying to get this example to work, but the display just a bunch of scan lines. It looks like it's also trying to display it vertical instead of horizontal. Any thoughts on how to fix that?
